# Sample workflow for building and deploying a VitePress site to GitHub Pages
name: Deploy VitePress site to Pages

on:
  # 触发条件：推送到 main 分支或手动触发
  push:
    branches: [main]
  workflow_dispatch:

# 权限设置
permissions:
  contents: read
  pages: write
  id-token: write

# 并发控制：避免同时部署
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 用于获取完整提交历史，支持 lastUpdated 功能

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm  # 根据包管理器选择 npm/pnpm/yarn

      - name: 配置 Pages
        uses: actions/configure-pages@v3

      - name: 安装依赖
        run: npm ci
        continue-on-error: false  # 依赖安装失败则终止

      - name: 构建 VitePress
        run: npm run docs:build
        continue-on-error: false  # 构建失败则终止

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist  # VitePress 默认输出目录

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build  # 依赖 build 作业完成
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3